export const GET_CATEGORIES_PENDING = '@COMPANY/GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = '@COMPANY/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = '@COMPANY/GET_CATEGORIES_FAILURE';

export const GET_IMAGES_PENDING = '@COMPANY/GET_IMAGES_PENDING';
export const GET_IMAGES_SUCCESS = '@COMPANY/GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = '@COMPANY/GET_IMAGES_FAILURE';